- name: Check if SNMPD is installed
  command: rpm -q net-snmp
  register: snmp_check
  ignore_errors: true
  when: "'RedHat' in ansible_distribution and ('8' in ansible_distribution_major_version or '9' in ansible_distribution_major_version)"
