- name: Check if SNMP Utils are installed
  command: rpm -q net-snmp-utils
  register: utils_check
  ignore_errors: true
  when: "'RedHat' in ansible_distribution and ('8' in ansible_distribution_major_version or '9' in ansible_distribution_major_version)"
