- name: Check OS version
  assert:
    that:
      - ansible_distribution == "RedHat" or ansible_distribution == "Red Hat Enterprise Linux"
      - ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9"
    fail_msg: "This role only supports Red Hat 8 and Red Hat 9."
  run_once: true

- debug:
    var: ansible_distribution
