- name: Reload firewalld
  command: 
    cmd: firewall-cmd --reload
  become: true
  when: firewalld_status.stdout == "active" and ('RedHat' in ansible_distribution and ('8' in ansible_distribution_major_version or '9' in ansible_distribution_major_version))