- name: Check if snmp service is in firewalld
  command:
    cmd: firewall-cmd --permanent --query-service={{ snmp_service_name }}
  register: snmp_service
  ignore_errors: true
  when: firewalld_status.stdout == "active" and ('RedHat' in ansible_distribution and ('8' in ansible_distribution_major_version or '9' in ansible_distribution_major_version))

- debug: 
    msg: "SNMP service is not in firewalld"
  when: snmp_service.stdout == "no" and ('RedHat' in ansible_distribution and ('8' in ansible_distribution_major_version or '9' in ansible_distribution_major_version))