- name: Restart SNMP service if configuration was updated
  service:
    name: snmpd
    state: restarted
  become: true
  when: snmpd_conf_update.changed and ('8' in ansible_distribution_major_version or '9' in ansible_distribution_major_version)
